import React from "react";
import Solar from "./Solar";

export default function PowerGenSolarPage() {
  return <Solar />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
