import React from "react";
import Recommend from "./Recommend";

export default function RecommendPage() {
  return <Recommend />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
