import React from "react";
import Billing from "./Billing";

export default function InvoicePage() {
  return <Billing />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
