import React from "react";
import CarbonAccounting from "./CarbonAccounting";

export default function EnergyPage() {
  return <CarbonAccounting />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
