import React from "react";
import Biogas from "./Biogas";

export default function PowerGenBiogasPage() {
  return <Biogas />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
