import React from "react";
import Summary from "./Summary";

export default function SummaryPage() {
  return <Summary />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
