import React from "react";
import AirCond from "./AirCond";

export default function AirCondPage() {
  return <AirCond />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
