import React from "react";
import Battery from "./Battery";

export default function PowerGenBatteryPage() {
  return <Battery />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
