import React from "react";
import SmartStreetLight from "./SmartStreetLight";

export default function AirCompressorPage() {
  return <SmartStreetLight />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
