import React from "react";
import Dashboard from "./Dashboard";

export default function OverviewPage() {
  return <Dashboard />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
