import React from "react";
import EvCharger from "./EvCharger";

export default function AirCompressorPage() {
  return <EvCharger />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
