import React from "react";
import Overview from "./Overview";

export default function PowerGenOverviewPage() {
  return <Overview />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
