import React from "react";
import IoT from "./IoT";

export default function IoTPage() {
  return <IoT />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
