"use client";
import React, { useMemo, useState, useCallback } from "react";
import {
  ResponsiveContainer,
  ComposedChart,
  AreaChart,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Bar,
  Area,
  ReferenceLine,
  Line,
  Brush,
  CartesianGrid,
} from "recharts";

export default function EnergyTrendChart({ type, dataProp }) {
  const [hiddenKeys, setHiddenKeys] = useState([]);

  // คำนวณ maxY โดยไม่ว่าจะมี data หรือไม่
  const maxY = useMemo(() => {
    if (!dataProp) return 0;
    return Math.max(
      ...(dataProp.consumption ?? []),
      ...(dataProp.generation ?? []),
      ...(dataProp.powerFromGrid ?? []),
      ...(dataProp.energyBaseline ?? []),
      0
    );
  }, [dataProp]);

  // ฟังก์ชันวัดความกว้างของข้อความสำหรับ margin ซ้าย
  const getTextWidth = (text, font = "12px sans-serif") => {
    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");
    context.font = font;
    return context.measureText(text).width;
  };

  // คำนวณ margin ซ้ายโดยอ้างอิงจากความกว้างของค่าที่ใหญ่สุด
  const leftMargin = useMemo(() => {
    const longestLabel = (-maxY).toLocaleString();
    const width = getTextWidth(longestLabel, "12px Roboto");
    return Math.max(40, Math.ceil(width + 10));
  }, [maxY]);

  // ฟังก์ชันจัดการการคลิก legend เพื่อซ่อน/แสดงกราฟ
  const handleLegendClick = useCallback(
    (e) => {
      const key = e.dataKey;
      setHiddenKeys((prev) =>
        prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
      );
    },
    []
  );

  const commonProps = {
    onClick: handleLegendClick,
  };

  // ถ้าไม่มีข้อมูล ให้แสดงข้อความนี้ และ return หลังจากเรียก hooks ทั้งหมดแล้ว
  if (!dataProp || !dataProp.timestamp || dataProp.timestamp.length === 0) {
    return (
      <div
        style={{
          width: "100%",
          height: "400px",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: 16,
          color: "#888",
          borderRadius: 12,
          border: "1px solid #ddd",
        }}
      >
        No data available
      </div>
    );
  }

  // เตรียม data สำหรับใช้ใน chart โดย map ตาม timestamp
  const data = dataProp.timestamp.map((timestamp, index) => ({
    day: timestamp,
    consumed: -1 * (dataProp.consumption?.[index] ?? 0),
    generated_mirror: dataProp.generation?.[index] ?? 0,
    purchased_mirror: dataProp.powerFromGrid?.[index] ?? 0,
    energy_base_line: -1 * (dataProp.energyBaseline?.[index] ?? 0),
  }));

  // ฟังก์ชัน render ชื่อหน่วย (kWh หรือ kW)
  const renderUnitLabel = () => (
    <text
      x={80}
      y={15}
      fill="currentColor"
      className="text-black dark:text-white"
      fontSize={15}
      fontWeight="bold"
    >
      {["month", "year", "lifetime"].includes(type) ? "kWh" : "kW"}
    </text>
  );

  // ถ้า type คือ month, year, หรือ lifetime ให้แสดง ComposedChart แบบ stacked bar + line
  if (["month", "year", "lifetime"].includes(type)) {
    return (
      <ResponsiveContainer width="100%" height={300}>
        <ComposedChart
          data={data}
          stackOffset="sign"
          barCategoryGap={10}
          margin={{ top: 40, right: 0, left: leftMargin, bottom: 0 }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="day" />
          <YAxis
            domain={[-maxY, maxY]}
            tickFormatter={(v) => Math.abs(v).toLocaleString()}
          />
          <Tooltip
            formatter={(value, name) => [
              `${Math.abs(Number(value)).toLocaleString()} kWh`,
              name,
            ]}
          />
          <Legend {...commonProps} />
          <ReferenceLine y={0} stroke="gray" />
          {renderUnitLabel()}
          <Bar
            dataKey="consumed"
            stackId="energy"
            name="Energy Consumed"
            fill="#FFB74D"
            hide={hiddenKeys.includes("consumed")}
          />
          <Bar
            dataKey="generated_mirror"
            stackId="energy"
            name="Generated by PV"
            fill="#81C784"
            hide={hiddenKeys.includes("generated_mirror")}
          />
          <Bar
            dataKey="purchased_mirror"
            stackId="energy"
            name="Purchased from grid"
            fill="#4FC3F7"
            hide={hiddenKeys.includes("purchased_mirror")}
          />
          <Line
            type="monotone"
            dataKey="energy_base_line"
            stroke="#E53935"
            strokeWidth={2}
            dot={true}
            name="Energy Baseline"
            hide={hiddenKeys.includes("energy_base_line")}
          />
          <Brush dataKey="day" height={30} stroke="#8884d8" />
        </ComposedChart>
      </ResponsiveContainer>
    );
  }

  // กรณีอื่น ๆ (เช่น daily หรือ hourly) ใช้ AreaChart
  return (
    <ResponsiveContainer width="100%" height={300}>
      <AreaChart data={data} margin={{ top: 40, right: 0, left: leftMargin, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="day" />
        <YAxis
          domain={[-maxY, maxY]}
          tickFormatter={(v) => Math.abs(v).toLocaleString()}
        />
        <Tooltip
          formatter={(value, name) => [
            `${Math.abs(Number(value)).toLocaleString()} kW`,
            name,
          ]}
        />
        <Legend {...commonProps} />
        <ReferenceLine y={0} stroke="gray" />
        {renderUnitLabel()}
        <Area
          type="monotone"
          dataKey="consumed"
          stroke="#FB8C00"
          fill="#FFE9CA"
          strokeWidth={2}
          name="Consumption Power"
          hide={hiddenKeys.includes("consumed")}
        />
        <Area
          type="monotone"
          dataKey="purchased_mirror"
          stroke="#808080"
          strokeWidth={2}
          fill="#fff"
          name="Power from grid"
          hide={hiddenKeys.includes("purchased_mirror")}
        />
        <Area
          type="monotone"
          dataKey="generated_mirror"
          stroke="#008001"
          fill="#deede8"
          strokeWidth={2}
          name="PV Power"
          hide={hiddenKeys.includes("generated_mirror")}
        />
        <Brush dataKey="day" height={30} stroke="#8884d8" />
      </AreaChart>
    </ResponsiveContainer>
  );
}
