import React from "react";
import EnergeyAnalysis from "./EnergyAnalysis";

export default function EnergyPage() {
  return <EnergeyAnalysis />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
