import React from "react";
import Invoice from "./Invoice";

export default function InvoicePage() {
  return <Invoice />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
