import { NextResponse } from "next/server";

const deviceTypeParameters = {
  0: [
    { id: 0, deviceTypeId: 0, field: "-", name: "-", unit: "-", isShow: true },
  ],
  1: [
    {
      id: 1,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "roomTemp",
      name: "Room Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 2,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "humidity",
      name: "Humidity",
      unit: "%",
      isShow: true,
    },
    {
      id: 3,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "setTemp",
      name: "Set Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 4,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "control",
      name: "Control",
      unit: "",
      isShow: true,
    },
    {
      id: 5,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "fan",
      name: "Fan Speed",
      unit: "",
      isShow: true,
    },
    {
      id: 6,
      deviceTypeId: 1,
      deviceTypeName: "hvac_split_type",
      field: "mode",
      name: "Mode",
      unit: "",
      isShow: true,
    },
  ],
  2: [
    {
      id: 7,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "supplyTemp",
      name: "Supply Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 8,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "supplyTempSetPoint",
      name: "Supply Temp Setpoint",
      unit: "°C",
      isShow: true,
    },
    {
      id: 9,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "returnTemp",
      name: "Return Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 10,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "vsdDrive",
      name: "VSD %Drive",
      unit: "Hz",
      isShow: true,
    },
    {
      id: 11,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "vsdPower",
      name: "VSD Power",
      unit: "kW",
      isShow: true,
    },
    {
      id: 12,
      deviceTypeId: 2,
      deviceTypeName: "hvac_ahu",
      field: "controlValve",
      name: "Control Valve",
      unit: "%",
      isShow: true,
    },
  ],
  3: [
    {
      id: 13,
      deviceTypeId: 3,
      deviceTypeName: "hvac_vav",
      field: "temp",
      name: "Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 14,
      deviceTypeId: 3,
      deviceTypeName: "hvac_vav",
      field: "airFlow",
      name: "Air Flow",
      unit: "CFM",
      isShow: true,
    },
    {
      id: 15,
      deviceTypeId: 3,
      deviceTypeName: "hvac_vav",
      field: "damper",
      name: "Damper",
      unit: "%",
      isShow: true,
    },
  ],
  4: [
    {
      id: 16,
      deviceTypeId: 4,
      deviceTypeName: "hvac_iot",
      field: "temp",
      name: "Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 17,
      deviceTypeId: 4,
      deviceTypeName: "hvac_iot",
      field: "humidity",
      name: "Humidity",
      unit: "%",
      isShow: true,
    },
    {
      id: 18,
      deviceTypeId: 4,
      deviceTypeName: "hvac_iot",
      field: "co2",
      name: "CO2",
      unit: "ppm",
      isShow: true,
    },
  ],
  5: [
    {
      id: 19,
      deviceTypeId: 5,
      deviceTypeName: "iot_indoor_temp_humid",
      field: "roomTemp",
      name: "Room Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 20,
      deviceTypeId: 5,
      deviceTypeName: "iot_indoor_temp_humid",
      field: "humidity",
      name: "Humidity",
      unit: "%",
      isShow: true,
    },
  ],
  6: [
    {
      id: 21,
      deviceTypeId: 6,
      deviceTypeName: "iot_outdoor_temp_humid",
      field: "temp",
      name: "Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 22,
      deviceTypeId: 6,
      deviceTypeName: "iot_outdoor_temp_humid",
      field: "humidity",
      name: "Humidity",
      unit: "%",
      isShow: true,
    },
  ],
  7: [
    {
      id: 23,
      deviceTypeId: 7,
      deviceTypeName: "iot_pressure_gauge",
      field: "pressure",
      name: "Pressure",
      unit: "bar",
      isShow: true,
    },
  ],
  8: [
    {
      id: 24,
      deviceTypeId: 8,
      deviceTypeName: "iot_power_meter",
      field: "power",
      name: "Power",
      unit: "kW",
      isShow: true,
    },
    {
      id: 25,
      deviceTypeId: 8,
      deviceTypeName: "iot_power_meter",
      field: "current",
      name: "Current",
      unit: "A",
      isShow: true,
    },
    {
      id: 26,
      deviceTypeId: 8,
      deviceTypeName: "iot_power_meter",
      field: "volt",
      name: "Volt",
      unit: "V",
      isShow: true,
    },
    {
      id: 27,
      deviceTypeId: 8,
      deviceTypeName: "iot_power_meter",
      field: "energy_import",
      name: "Energy import",
      unit: "kWh",
      isShow: true,
    },
    {
      id: 28,
      deviceTypeId: 8,
      deviceTypeName: "iot_power_meter",
      field: "energy_export",
      name: "Energy export",
      unit: "kWh",
      isShow: true,
    },
  ],
  9: [
    {
      id: 29,
      deviceTypeId: 9,
      deviceTypeName: "iot_inverter",
      field: "power",
      name: "Power",
      unit: "kW",
      isShow: true,
    },
    {
      id: 30,
      deviceTypeId: 9,
      deviceTypeName: "iot_inverter",
      field: "current",
      name: "Current",
      unit: "A",
      isShow: true,
    },
    {
      id: 31,
      deviceTypeId: 9,
      deviceTypeName: "iot_inverter",
      field: "volt",
      name: "Volt",
      unit: "V",
      isShow: true,
    },
    {
      id: 32,
      deviceTypeId: 9,
      deviceTypeName: "iot_inverter",
      field: "energy",
      name: "Energy",
      unit: "kWh",
      isShow: true,
    },
  ],
  10: [
    {
      id: 33,
      deviceTypeId: 10,
      deviceTypeName: "iot_flow_meter",
      field: "flow",
      name: "Flow",
      unit: "gal/min",
      isShow: true,
    },
  ],
  11: [
    {
      id: 34,
      deviceTypeId: 11,
      deviceTypeName: "iot_motion_sensor",
      field: "detect",
      name: "Detected",
      unit: "",
      isShow: true,
    },
  ],
  12: [
    {
      id: 35,
      deviceTypeId: 12,
      deviceTypeName: "iot_lighting",
      field: "status",
      name: "Status",
      unit: "",
      isShow: true,
    },
  ],
  13: [
    {
      id: 36,
      deviceTypeId: 13,
      deviceTypeName: "iot_counter",
      field: "piece",
      name: "Pieces",
      unit: "ea",
      isShow: true,
    },
  ],
  14: [
    {
      id: 37,
      deviceTypeId: 14,
      deviceTypeName: "iot_smart_ir",
      field: "setTemp",
      name: "Set Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 38,
      deviceTypeId: 14,
      deviceTypeName: "iot_smart_ir",
      field: "control",
      name: "Control",
      unit: "",
      isShow: false,
    },
    {
      id: 39,
      deviceTypeId: 14,
      deviceTypeName: "iot_smart_ir",
      field: "fan",
      name: "Fan Speed",
      unit: "",
      isShow: false,
    },
    {
      id: 40,
      deviceTypeId: 14,
      deviceTypeName: "iot_smart_ir",
      field: "mode",
      name: "Mode",
      unit: "",
      isShow: false,
    },
  ],
  15: [
    {
      id: 41,
      deviceTypeId: 15,
      deviceTypeName: "iot_efficiency",
      field: "efficiency",
      name: "Efficiency",
      unit: "%",
      isShow: true,
    },
  ],
  17: [
    {
      id: 42,
      deviceTypeId: 17,
      deviceTypeName: "iot_co2_sensor",
      field: "co2",
      name: "CO2",
      unit: "ppm",
      isShow: true,
    },
  ],
  18: [
    {
      id: 43,
      deviceTypeId: 18,
      deviceTypeName: "iot_water_meter",
      field: "flow",
      name: "Flow",
      unit: "m3/min",
      isShow: true,
    },
  ],
  19: [
    {
      id: 44,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "temp",
      name: "Temp",
      unit: "°C",
      isShow: true,
    },
    {
      id: 45,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "power",
      name: "Power",
      unit: "kW",
      isShow: true,
    },
    {
      id: 46,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "model",
      name: "Model",
      unit: "",
      isShow: false,
    },
    {
      id: 47,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "waste",
      name: "Waste",
      unit: "ea",
      isShow: true,
    },
    {
      id: 48,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "counter",
      name: "Counter",
      unit: "ea",
      isShow: true,
    },
    {
      id: 49,
      deviceTypeId: 19,
      deviceTypeName: "iot_heater",
      field: "control",
      name: "Control",
      unit: "",
      isShow: true,
    },
  ],
  20: [
    {
      id: 50,
      deviceTypeId: 20,
      deviceTypeName: "iot_heater_water",
      field: "temp",
      name: "Temp",
      unit: "°F",
      isShow: true,
    },
  ],
};
export async function GET(request, { params }) {
  const deviceTypeId = params.deviceTypeId;
  const responseData = deviceTypeParameters[deviceTypeId];

  const filterResponse = responseData.filter((item) => item.isShow === true);

  if (responseData) {
    return NextResponse.json(filterResponse);
  }
  return NextResponse.json({ message: "no data" });
}
