import React from "react";
import Chiller from "./Chiller";

export default function ChillerPage() {
  return <Chiller />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
