import React from "react";
import Hvac from "./Hvac";

export default function HvacPage() {
  return <Hvac />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
