import React from "react";
import Energy from "./Energy";

export default function EnergyPage() {
  return <Energy />;
}

export const metadata = {
  title: "ENZY",
  description: "Generated by create next app",
};
